### ISSUE TITLE
Counter stuck at 47

### ISSUE THREAD

**Issue by bajohnso-uci** [whuang37/biondi_body_client#24]
I actually have analyzed about 65 bodies.

Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1883, in __call__
  File "tkinter\__init__.py", line 804, in callit
  File "biondi_body_client.py", line 184, in update_count
  File "file_management.py", line 103, in count_bodies
sqlite3.OperationalError: too many SQL variables

**Comment by whuang37** [comment]
Fixed. self.all_bodies was being appended as well as no copy of the list was made
